#!/usr/bin/bash

while [ "$#" != 0 ];
do
	echo ARG: $1
	case $1 in
		--option1=*|-o1=*)
			OPTION1=${arg#*=}
			shift
			;;
		--option1|-o1)
			echo 'Selected: -o1'
			OPTION1="$2"
			echo '$2 is' $OPTION1
			shift
			shift
			;;
		--option2=*|-o2=*)
			echo 'Selected: -o2='
			OPTION2=${arg#*=}
			shift
			;;
		--option2|-o2)
			echo 'Selected: -o2'
			OPTION2="$2"
			shift
			shift
			;;
		--*|-*)
			echo 'Err: Unknown option'
			exit 1
	esac
done
